config/routes.rb
Rails.application.routes.draw do

  resources :invitations, only: [:new, :create]
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root to: 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :date, :description, :location, presence: true
  has_many :invitations, foreign_key: 'attended_event_id', dependent: :destroy
  has_many :attendees, through: :invitations
  has_one_attached :image
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  scope :prev_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date > ?', Time.now) }

  def unattendees
    User.all - attendees
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee_id, uniqueness: { scope: :attended_event_id,
                                        message: 'can created only one invitation for person for party' }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :events, foreign_key: 'creator_id'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations

  def invited?(event_id)
    attended_events.exists?(event_id)
  end

  def can_invite_others?(event_id)
    case1 = attended_events.exists?(event_id)
    case2 = (Event.find(event_id).creator.id == id)

    case1 || case2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :restrict_new_event
  after_action :invite_creator, only: [:create]
  def index
    @events = Event.all.order('created_at DESC')
    @upcoming_events = Event.upcoming_events
    @prev_events = Event.prev_events

    redirect_to new_session_path unless signed_in?
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_path(current_user)
  end

  def show
    @event = Event.find(params[:id])
    @user = @event.creator

    if @event.date < Time.now
      render :show_past
    elsif current_user.can_invite_others?(@event.id)
      render :show
    else
      render :show_not_invited
    end
  end

  def invite_creator
    Invitation.create(
      attendee_id: current_user.id,
      attended_event_id: @event.id
    )
  end

  private

  def restrict_new_event
    redirect_to new_session_path unless signed_in?
  end

  def event_params
    params.require(:event).permit(:description, :date, :location, :time)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation
  end

  def create
    @event_id = params[:information][:event_id]
    @user = User.find(params[:information][:unattendee_id])

    invitation = @user.invitations.build(attended_event_id: @event_id)

    redirect_to event_path(@event_id) if invitation.save
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @names = User.all
    @user = User.new
  end

  def create
    @name = params[:user][:name]
    @user = User.new(name: @name)
    if User.find_by(name: @name).nil?
      @names = User.all
      render :new
    else
      @id = User.find_by(name: @name).id
      session[:current_user_id] = @id
      redirect_to user_path(@id)
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

  private

  def user_sign_in_params
    params.require(:user).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user = User.find_by(name: @user.name)
      signed_in? ? redirect_to(new_user_path) : create_session_and_redirect(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(current_user_id)
    @events = @user.events.order(date: :desc)

    @upcoming_events = @user.attended_events.upcoming_events
    @prev_events = @user.attended_events.prev_events
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def welcome_links
    ('Welcome ' + current_user.name) if signed_in?
  end

  def my_page_links
    return unless signed_in?

    @class_name = if %r{^/users/\d+}.match(current_path)
                    'nav-link text-success'
                  else
                    'nav-link'
                  end
    render 'layouts/my_events_links'
  end

  def sign_out_links
    if signed_in?
      render 'sessions/sign_in'
    else
      render 'sessions/sign_out'
    end
  end

  def create_event_links
    render 'layouts/create_new_event' if signed_in?
  end

  def events_calendar_links
    @class_name = current_path == '/' || current_path == '/events' ? 'nav-link text-success ' : 'nav-link'
    render 'layouts/events_calendar_links' if signed_in?
  end

  private

  def class_namer(path, color)
    current_path == path ? "nav-link text-#{color}" : 'nav-link'
  end

  def current_path
    request.env['PATH_INFO']
  end

  def sign_up_links
    render 'sessions/sign_up' unless signed_in?
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def delete_event_button
    render 'events/delete_event' if current_user.id == @event.creator.id
  end

  def delete_upcoming_event_button(event)
    return unless event.date > Time.now

    class_name = 'btn btn-danger btn-sm px-2'
    link_to 'Cancel', event_path(event.id), method: :delete,
                                            class: class_name, data: { confirm: 'You are going to delete this event?' }
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find(current_user_id) if signed_in?
  end

  def current_user_id
    session[:current_user_id]
  end

  def signed_in?
    session[:current_user_id].nil? ? false : true
  end

  def create_session(user_id)
    session[:current_user_id] = user_id
  end

  def create_session_and_redirect(user)
    create_session(user.id)
    redirect_to user_path(user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def upcoming?(event)
    event.date > Time.now
  end

  def badge_selector(event)
    if upcoming?(event)
      render 'upcoming_event_badge'
    else
      render 'prev_event_badge'
    end
  end
end

app/views/events/_delete_event.html.erb
<table class="table mt-0">
  <tbody>
    <tr>
      <td class="text-center">
        <h3>
          <%= link_to 'Cancel This Event', event_path(@event.id),
        method: :delete,
        class: "btn btn-danger btn-lg px-5",
        data: { confirm: 'You are going to delete this event?' } %>
      </h3>
    </td>
    </tr>
  </tbody>
</table>

app/views/events/_delete_upcoming_event.html.erb
<span>
  <%= link_to 'Cancel', event_path(event.id), method: :delete, class: "btn btn-danger btn-sm px-2" %>
</span>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h3 class="text-center mt-4 text-white">
<span><i class="fas fa-forward"></i></span>
Upcoming Events
</h3>

<table class="table w-75 m-auto">
    <thead class="thead-dark">
        <tr>
          <th>Status</th>
            <th>Description</th>
            <th>Creator</th>
            <th>Date</th>
            <th>Location</th>
            <th class="text-center">Show Event Page</th>
        </tr>
    </thead>
    <tbody>
      <% Event.all.upcoming_events.each do |event| %>
        <tr class="table-primary">
            <td class="align-middle">
              <span class="badge badge-success p-2">
                Upcoming
              </span>
            </td>
            <td class="text-success align-middle"><strong><%= event.description %></strong></td>
            <td class="align-middle"><%= event.creator.name %></td>
            <td class="align-middle"><%= event.date.strftime('%Y-%m-%d %H:%M %Z') %></td>
            <td class="align-middle"><%= event.location %></td>
            <td class="text-center"><%= link_to 'Show', event_path(event.id), class: "btn btn-success btn-sm px-5" %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<h3 class="text-center mt-4 text-white">
<span><i class="fas fa-backward"></i></span>
Previous Events
</h3>
<table class="table w-75 m-auto mb-5">
    <thead class="thead-dark">
        <tr>
          <th>Status</th>
            <th>Description</th>
            <th>Creator</th>
            <th>Date</th>
            <th>Location</th>
            <th class="text-center">Show Event Page</th>
        </tr>
    </thead>
    <tbody>
      <% Event.all.prev_events.each do |event| %>
        <tr class="table-secondary">
          <td class="align-middle"><span class="badge badge-warning p-2">Past</span></td>
            <td class="text-secondary align-middle"><strong><%= event.description %></strong></td>
            <td class="align-middle"><%= event.creator.name %></td>
            <td class="align-middle"><%= event.date.strftime('%Y-%m-%d %H:%M %Z') %></td>
            <td class="align-middle"><%= event.location %></td>
            <td class="text-center align-middle"><%= link_to 'Show', event_path(event.id), class: "btn btn-warning btn-sm px-5" %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<div class="mb-5"></div>

app/views/events/new.html.erb
<div class="container text-center">

  <div class="row text-center">
    <div class="col-xl-12 text-center">
      <h2 class="my-5 text-center display-4">
        <span class="badge badge-warning text-white">
      CREATE NEW EVENT
        </span>
      </h2>

        <%= form_for @event do |f| %>

          <table class="table">
            <tr class="table-primary">
              <td>
                <h4 class="p-3 mb-0">
                  <%= f.label :description %>
                  <span class="ml-3">
                  <i class="fas fa-info"></i>
                  </span>
                  </h4>
              </td>
              <td>
                <%= f.text_field :description, placeholder: "Sky Diving", required: true, class: "w-100 p-3"  %>
              </td>
            </tr>
            <tr class="table-success">
              <td>

                <h4 class="p-3 mb-0">
                  <%= f.label :date %>
                  <span class="ml-3">
                  <i class="fas fa-table"></i>
                  </span>
                </h4>
              </td>
              <td>
                <%= f.datetime_field :date, required: true, class: "w-100 p-3" %>
              </td>
            </tr>
            <tr class="table-info">
              <td>
                <h4 class="p-3 mb-0">
                <%= f.label :location %>
                <span class="ml-3">
                  <i class="fas fa-location-arrow"></i>
                </span>
                </h4>
              </td>
              <td>
                <%= f.text_field :location, placeholder: "Greece/Patras", required: true, class: "w-100 p-3" %>
              </td>
            </tr>
            <tr>
              <td >
              </td>
            </tr>
          </table>
          <%= f.submit :Create, class: "btn btn-success p-3 px-5 w-50" %>
        <% end %>

    </div>
  </div>

</div>

app/views/events/show.html.erb
<div class="container-fluid mt-1 px-5">
  <div class="row">
    <div class="col-xl-12">
      <h2 class="my-5 text-center display-4">
        <span class="text-white">
          <i class="fas fa-glass-cheers"></i>
        </span>
        <span class="badge badge-warning">
        <%= @event.description %>
        <span class="badge badge-pill badge-success"> <%=@event.attendees.count%> </span>
        </span>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-4">


      <table class="table table-dark mb-0">
        <tbody>
          <tr>
            <td class="text-center"><h3>Event Details</h3></td>
          </tr>
        </tbody>
      </table>
      <table class="table mb-0">
        <tbody>
          <tr class="table-primary">
            <td class="lead">Creator</td>
            <td class="text-center text-danger"><strong><%= @user.name %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Location</td>
            <td class="text-center text-danger"><strong><%= @event.location %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Date</td>
            <td class="text-center text-danger"><strong><%= @event.date.strftime('%Y-%m-%d %H:%M %Z') %></strong></td>
          </tr>
        </tbody>
      </table>
    <%= delete_event_button %>
    </div>
    <div class="col-xl-4">

      <table class="table mb-0">
        <tbody>
          <tr>
            <td class="text-center text-white"><h5>Attendees</h5></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
          <thead class="thead-dark">
              <tr>
                <th></th>
                <th>Name</th>

              </tr>
          </thead>
          <tbody>
            <% @event.attendees.each_with_index do |attendee, index| %>
              <tr class="table-success">
                <td><%= index + 1 %></td>
                <td><%= attendee.name %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>

    <div class="col-xl-4">
      <table class="table mb-0">
        <tbody>
          <tr>
            <td class="text-center text-white"><h5>You can invite these people!</h5></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
          <thead class="thead-dark">
              <tr >
                <th></th>
                <th>Name</th>
                <th class="text-center">Invite</th>
              </tr>
          </thead>
          <tbody>
            <% @event.unattendees.each_with_index do |unattendee, index| %>
              <tr class="table-warning">
                <td><%= index + 1 %></td>
                <td><%= unattendee.name %></td>
                <td class="text-center"><%= link_to 'Invite',
                  invitations_path("information"=>{ unattendee_id: unattendee.id, event_id: @event.id}),
                  method: :create, class: "btn btn-success btn-sm px-5 w-75" %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>
    </div>
  </div class="row">
</div>

app/views/events/show_not_invited.html.erb
<div class="container-fluid mt-1 px-5">
  <div class="row">
    <div class="col-xl-12">
      <h2 class="my-5 text-center display-4">
        <span class="badge badge-warning">
        <%= @event.description %>
        <span class="badge badge-pill badge-success"> <%=@event.attendees.count%> </span>
        </span>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-4">


      <table class="table table-dark mb-0">
        <tbody>
          <tr>
            <td class="text-center"><h3>Event Details</h3></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <tbody>
          <tr class="table-primary">
            <td class="lead">Creator</td>
            <td class="text-center text-danger"><strong><%= @user.name %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Location</td>
            <td class="text-center text-danger"><strong><%= @event.location %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Date</td>
            <td class="text-center text-danger"><strong><%= @event.date.strftime('%Y-%m-%d %H:%M %Z') %></strong></td>
          </tr>
        </tbody>
      </table>

    </div>
    <div class="col-xl-4">

      <table class="table mb-0">
        <tbody>
          <tr>
            <td class="text-center"><h5>Who joined this Event?</h5></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
          <thead class="thead-dark">
              <tr>
                <th></th>
                <th>Name</th>

              </tr>
          </thead>
          <tbody>
            <% @event.attendees.each_with_index do |attendee, index| %>
              <tr class="table-success">
                <td><%= index + 1 %></td>
                <td><%= attendee.name %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>
    <div class="col-xl-4">
      <h4 class="my-5 text-center display-4 text-wrap">
        <span class="badge badge-secondary text-wrap">
        You can't invite people to this event.
        </span>
      </h4>
    </div>

    </div>
  </div class="row">
</div>

app/views/events/show_past.html.erb
<div class="container-fluid mt-1 px-5">
  <div class="row">
    <div class="col-xl-12">
      <h2 class="my-5 text-center display-4">
        <span class="badge badge-warning">
        <%= @event.description %>
        <span class="badge badge-pill badge-success"> <%=@event.attendees.count%> </span>
        </span>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-4">


      <table class="table table-dark mb-0">
        <tbody>
          <tr>
            <td class="text-center"><h3>Event Details</h3></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <tbody>
          <tr class="table-primary">
            <td class="lead">Creator</td>
            <td class="text-center text-danger"><strong><%= @user.name %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Location</td>
            <td class="text-center text-danger"><strong><%= @event.location %></strong></td>
          </tr>
          <tr class="table-primary">
            <td class="lead">Date</td>
            <td class="text-center text-danger"><strong><%= @event.date.strftime('%Y-%m-%d %H:%M %Z') %></strong></td>
          </tr>
        </tbody>
      </table>

    </div>
    <div class="col-xl-4">

      <table class="table mb-0">
        <tbody>
          <tr>
            <td class="text-center"><h5>Who joined this Event?</h5></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
          <thead class="thead-dark">
              <tr>
                <th></th>
                <th>Name</th>

              </tr>
          </thead>
          <tbody>
            <% @event.attendees.each_with_index do |attendee, index| %>
              <tr class="table-success">
                <td><%= index + 1 %></td>
                <td><%= attendee.name %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
    </div>
    <div class="col-xl-4">
      <h2 class="my-5 text-center display-4">
        <span class="badge badge-secondary">
        Past Event
        </span>
      </h2>
    </div>

    </div>
  </div class="row">
</div>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/new.html.erb
<h1>Invitations#new</h1>
<p>Find me in app/views/invitations/new.html.erb</p>

app/views/layouts/_create_new_event.html.erb
<div class="d-flex align-items-center">
<i class="far fa-plus-square"></i>
<%= link_to 'Create New Event', new_event_path, class: class_namer('/events/new', 'warning') %>
</div>

app/views/layouts/_events_calendar_links.html.erb
<div class="d-flex align-items-center">
<i class="far fa-calendar-alt"></i>
<%= link_to 'Events Calendar', events_path, class: @class_name %>
</div>

app/views/layouts/_my_events_links.html.erb
<div class="d-flex align-items-center">
<i class="far fa-user"></i>
<%= link_to "My Events (#{current_user.name})", user_path(current_user_id), class: @class_name %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <span class="px-1">
    <i class="fas fa-ring"></i>
  </span>
  <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav d-flex justify-content-around w-75">
      <%= create_event_links %>
      <%= events_calendar_links %>
      <%= my_page_links %>
    </ul>
    <ul class="navbar-nav ml-auto d-flex">
      <%= sign_up_links %>

      <%= sign_out_links %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2c6133bcaa.js" crossorigin="anonymous"></script>
    <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_prev_event_badge.html.erb
<span class="badge badge-warning p-2">Past</span>

app/views/users/_prev_event_table.html.erb
<table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Description</th>
                <th>Location</th>
                <th>Date</th>
                <th>Event Page</th>
            </tr>
        </thead>
        <tbody>
        <% @prev_events.each do |event| %>
            <tr class="table-secondary">
                <td class="align-middle"><%= event.description %></td>
                <td class="align-middle"><%= event.location %></td>
                <td class="align-middle"><%= event.date.strftime('%Y-%m-%d %H:%M %Z') %></td>
                <td class="align-middle"><%= link_to 'Show', event_path(event.id), class: "btn btn-warning btn-sm px-4" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/users/_upcom_events_table.html.erb
<table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Description</th>
                <th>Location</th>
                <th>Date</th>
                <th>Event Page</th>
            </tr>
        </thead>
        <tbody>
        <% @upcoming_events.each do |event| %>
            <tr class="table-primary">
                <td class="align-middle"><%= event.description %></td>
                <td class="align-middle"><%= event.location %></td>
                <td class="align-middle"><%= event.date.strftime('%Y-%m-%d %H:%M %Z') %></td>
                <td class="align-middle"><%= link_to 'Show', event_path(event.id), class: "btn btn-success btn-sm px-4" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/users/_upcoming_event_badge.html.erb
<span class="badge badge-success p-2">Upcoming</span>

app/views/users/new.html.erb
<h5 class="my-5 text-center text-warning display-4">

Create a new user with name...

</h5>

<div class="form-signin w-25 m-auto">
  <%= form_for @user, class: 'form-signin w-25 m-auto' do |f| %>
    <%= f.label :name, class: 'sr-only'  %>
    <%= f.text_field :name, placeholder: 'New user name',
    required: true, class: 'form-control p-3 h3 text-center py-4' %>
    <%= f.submit 'Create', class: 'btn btn-lg btn-warning btn-block mt-5' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid w-100 px-5 mb-5">
  <h3 class="text-center ml-5 mt-4 text-white">
    Event List <strong> <%= @user.name %> </strong> Created
    <span class="btn btn-success ml-5 p-2">
      <%= link_to '+ Create New Event', new_event_path, class: "text-white p-2 nav-link link-color-danger" %>
    </span>

  </h3>
  <div class="row mb-5 p-0">
    <div class="col-xl-12">
      <table class="table">
          <thead class="thead-dark">
              <tr>
                <th>Status</th>
                <th>Description</th>
                <th>Creator</th>
                <th>Date</th>
                <th>Location</th>
                <th>Event Page</th>
                <th>Delete</th>
              </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
              <tr class="table-primary align-middle">
                <td class="align-middle">
                  <%= badge_selector(event) %>
                </td>
                <td class="align-middle">
                  <%= event.description %>
                  <div class="badge badge-pill badge-info">
                    <%= event.attendees.count %>
                  </div> 
                </td>
                <td class="align-middle"><%= event.creator.name %></td>
                <td class="align-middle"><%= event.date.strftime('%Y-%m-%d %H:%M %Z') %></td>
                <td class="align-middle"><%= event.location %></td>
                <td class="align-middle"><%= link_to 'Details', event_path(event.id), class: "btn btn-success btn-sm px-5" %></td>
                <td class="align-middle"><%= delete_upcoming_event_button(event) %></td>
              </tr>
              <% end %>
          </tbody>
      </table>

    </div>
  </div>
  <h3 class="text-center my-4 text-white">Event List <strong> <%= @user.name %> </strong> Invited </h3>
  <div class="row">
    <div class="col-xl-6">
      <h5 class="text-center my-1 text-white">Upcoming</h5>
      <%= render 'upcom_events_table' %>
    </div>
    <div class="col-xl-6">
      <h5 class="text-center my-1 text-white">Previous</h5>
      <%= render 'prev_event_table' %>
    </div>
  </div>
</div>